name: Assign Issue Based on Webhook

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook to get user
        id: call_webhook
        uses: actions/github-script@v7
        with:
          script: |
            const response = await fetch('${{ secrets.WEBHOOK_URL }}', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-ddn-project-id': '${{ secrets.DDN_PROJECT_ID }}',
                'authorization': 'api-key ${{ secrets.PROMPTQL_API_KEY }}'
              },
              body: JSON.stringify({
                input: [{
                  description: `${{ github.event.issue.title }}\n\n${{ github.event.issue.body }}`
                }]
              })
            });

            const data = await response.json();
            console.log('Webhook response:', JSON.stringify(data, null, 2));

            // Check if output.data exists and has elements
            const assigneeData = data?.output?.data || [];
            console.log(`Number of assignees returned: ${assigneeData.length}`);

            // Extract first assignee from available data
            let assignees = "";
            if (assigneeData.length > 0) {
              const assignee = assigneeData[0]?.name;
              if (assignee && assignee !== "null") {
                assignees = assignee;
                console.log(`Assignee: ${assignee}`);
              }
            }

            if (!assignees) {
              console.log("No valid assignee found");
            } else {
              console.log(`Final assignee: ${assignees}`);
            }

            core.setOutput('assignees', assignees);
            return assignees;

      - name: Assign issue
        if: steps.call_webhook.outputs.assignees != ''
        run: |
          assignee="${{ steps.call_webhook.outputs.assignees }}"
          echo "Attempting to assign: $assignee"

          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
            -d "{\"assignees\": [\"$assignee\"]}")

          echo "Assignment response: $response"

          # Check if assignment was successful
          if echo "$response" | jq -e '.message' > /dev/null 2>&1; then
            echo "Assignment failed: $(echo "$response" | jq -r '.message')"
            exit 1
          else
            echo "Successfully assigned issue to: $assignee"
          fi
