name: Assign Issue Based on Webhook

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook to get user
        id: call_webhook
        run: |
          response=$(curl -s -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -H "x-ddn-project-id: ${{ secrets.DDN_PROJECT_ID }}" \
            -H "authorization: api-key ${{ secrets.PROMPTQL_API_KEY }}" \
            -d '{"input": [{"description": "${{ github.event.issue.title }}\n\n${{ github.event.issue.body }}"}]}')
          echo "Webhook response: $response"

          # Check if output.data exists and has elements
          data_length=$(echo $response | jq -r '.output.data | length // 0')
          echo "Number of assignees returned: $data_length"

          # Extract first assignee from available data
          assignees=""
          if [ "$data_length" -gt 0 ]; then
            assignee=$(echo $response | jq -r '.output.data[0].name // empty')
            if [ ! -z "$assignee" ] && [ "$assignee" != "null" ]; then
              assignees="$assignee"
              echo "Assignee: $assignee"
            fi
          fi

          if [ -z "$assignees" ]; then
            echo "No valid assignee found"
          else
            echo "Final assignee: $assignees"
          fi

          echo "assignees=$assignees" >> $GITHUB_OUTPUT

      - name: Assign issue
        if: steps.call_webhook.outputs.assignees != ''
        run: |
          assignee="${{ steps.call_webhook.outputs.assignees }}"
          echo "Attempting to assign: $assignee"

          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
            -d "{\"assignees\": [\"$assignee\"]}")

          echo "Assignment response: $response"

          # Check if assignment was successful
          if echo "$response" | jq -e '.message' > /dev/null 2>&1; then
            echo "Assignment failed: $(echo "$response" | jq -r '.message')"
            exit 1
          else
            echo "Successfully assigned issue to: $assignee"
          fi
